import time
import pyautogui as pya
import spell_index as farm

farm.wait_for_image('Mount_Olympus_Floor_Pattern')
farm.game_click()
pya.keyDown('W')
time.sleep(0.55)
pya.keyUp('W')
pya.keyDown("x")
time.sleep(1)
pya.keyUp("x")
time.sleep(3)
farm.spell_click(farm.spell_maker("More_Button"), 0, 0.6)
time.sleep(1)
farm.spell_click(farm.spell_maker("Done_Button"), 0, 0.6)
time.sleep(1)
pya.keyDown('A')
time.sleep(0.55)
pya.keyUp('A')
pya.keyDown('W')
time.sleep(5.28)
pya.keyUp('W')
pya.keyDown('D')
time.sleep(0.30)
pya.keyUp('D')
pya.keyDown('W')
time.sleep(3.07)
pya.keyUp('W')
pya.keyDown('A')
time.sleep(0.53)
pya.keyUp('A')
pya.keyDown('W')
time.sleep(1.00)
pya.keyUp('W')
pya.keyDown('D')
time.sleep(0.15)
pya.keyUp('D')
pya.keyDown('W')
time.sleep(6.65)
pya.keyUp('W')
pya.keyDown('A')
time.sleep(0.70)
pya.keyUp('A')
pya.keyDown('W')
time.sleep(3.82)
pya.keyUp('W')
pya.keyDown('A')
time.sleep(0.53)
pya.keyUp('A')
pya.keyDown('W')
time.sleep(4.76)
pya.keyUp('W')
pya.keyDown('A')
time.sleep(0.09)
pya.keyUp('A')
pya.keyDown('W')
time.sleep(3.82)
pya.keyUp('W')
