import time
import pyautogui as pya
import spell_index as farm

farm.wait_for_image("Mount_Olympus_Floor_Pattern")
pya.keyDown("w")
time.sleep(0.49)
pya.keyUp("w")
farm.spell_click(farm.spell_maker("More_Button"), 0, 0.6)
time.sleep(1)
farm.spell_click(farm.spell_maker("Done_Button"), 0, 0.6)
time.sleep(1)
pya.keyDown("a")
time.sleep(0.48)
pya.keyUp("a")
time.sleep(0.956)
pya.keyDown("w")
time.sleep(0.296)
pya.keyDown("d")
time.sleep(0.11)
pya.keyUp("d")
time.sleep(3.683)
pya.keyDown("d")
time.sleep(0.022)
pya.keyUp("d")
time.sleep(2.020)
pya.keyDown("a")
